import { CampaignServingSnapshotService } from './campaign-serving-snapshot.service';
import { CampaignCacheRepository } from './repository/campaign.cache.repository.interface';
import type { CachedCampaign } from './types/campaign.types';
import { ConfigService } from '@nestjs/config';

describe('CampaignServingSnapshotService', () => {
  const embedding = Array.from({ length: 384 }, (_, index) => index / 384);

  const buildCampaign = (
    id: string,
    embeddingTags: Record<string, number[]> = { tag: embedding }
  ): CachedCampaign => ({
    id,
    userId: 1,
    title: id,
    content: 'content',
    image: null,
    url: 'https://example.com',
    maxCpc: 100,
    dailyBudget: 1000,
    totalBudget: 10000,
    dailySpent: 0,
    totalSpent: 0,
    lastResetDate: new Date().toISOString(),
    isHighIntent: false,
    status: 'ACTIVE',
    startDate: new Date(Date.now() - 60_000).toISOString(),
    endDate: new Date(Date.now() + 60_000).toISOString(),
    createdAt: new Date().toISOString(),
    deletedAt: null,
    tags: ['tag'],
    embeddingTags,
  });

  const buildRepository = (campaigns: CachedCampaign[]) =>
    ({
      getAllCampaigns: jest.fn().mockResolvedValue(campaigns),
      findCampaignCachesByIds: jest.fn((ids: string[]) =>
        Promise.resolve(
          campaigns.filter((campaign) => ids.includes(campaign.id))
        )
      ),
    }) as unknown as CampaignCacheRepository & {
      getAllCampaigns: jest.Mock;
      findCampaignCachesByIds: jest.Mock;
    };

  const configService = {
    get: jest.fn((key: string, defaultValue?: string) =>
      key === 'RTB_CAMPAIGN_SOURCE' ? 'local_snapshot' : defaultValue
    ),
  } as unknown as ConfigService;

  it('builds the initial snapshot only once for concurrent reads', async () => {
    const campaign = buildCampaign('c1');
    const repository = buildRepository([campaign]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const [first, second] = await Promise.all([
      service.findCampaignsByIds(['c1']),
      service.findCampaignsByIds(['c1']),
    ]);

    expect(first.map((item) => item.id)).toEqual(['c1']);
    expect(second.map((item) => item.id)).toEqual(['c1']);
    expect(first[0].embeddingTags?.tag).toBeInstanceOf(Float32Array);
    expect(repository.getAllCampaigns).toHaveBeenCalledTimes(1);
    expect(repository.findCampaignCachesByIds).not.toHaveBeenCalled();
  });

  it('returns campaigns in ANN ID order', async () => {
    const first = buildCampaign('c1');
    const second = buildCampaign('c2');
    const repository = buildRepository([first, second]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const campaigns = await service.findCampaignsByIds(['c2', 'c1']);

    expect(campaigns.map((campaign) => campaign.id)).toEqual(['c2', 'c1']);
  });

  it('repairs a campaign whose embeddings were generated by another process', async () => {
    const incomplete = buildCampaign('c1', {});
    const completed = buildCampaign('c1');
    const repository = buildRepository([incomplete]);
    repository.findCampaignCachesByIds.mockResolvedValue([completed]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const campaigns = await service.findCampaignsByIds(['c1']);

    expect(repository.findCampaignCachesByIds).toHaveBeenCalledWith(['c1']);
    expect(campaigns.map((campaign) => campaign.id)).toEqual(['c1']);
    expect(campaigns[0].embeddingTags?.tag).toBeInstanceOf(Float32Array);
  });

  it('applies cache mutations without rebuilding the whole snapshot', async () => {
    const first = buildCampaign('c1');
    const second = buildCampaign('c2');
    const repository = buildRepository([first]);
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );
    await service.findCampaignsByIds(['c1']);
    const previousVersion = service.getMetadata().version;

    service.onCampaignCacheUpserted({ campaign: second });
    service.onCampaignCacheRemoved({ campaignId: 'c1' });

    await expect(
      service
        .findCampaignsByIds(['c2'])
        .then((campaigns) => campaigns.map((campaign) => campaign.id))
    ).resolves.toEqual(['c2']);
    expect(service.getMetadata()).toMatchObject({
      version: previousVersion + 2,
      size: 1,
    });
  });

  it('does not lose mutations that arrive while the initial snapshot is loading', async () => {
    const stale = buildCampaign('c1');
    const updated = { ...buildCampaign('c1'), title: 'updated' };
    let finishLoading: ((campaigns: CachedCampaign[]) => void) | undefined;
    const repository = buildRepository([]);
    repository.getAllCampaigns.mockImplementation(
      () =>
        new Promise<CachedCampaign[]>((resolve) => {
          finishLoading = resolve;
        })
    );
    const service = new CampaignServingSnapshotService(
      repository,
      configService
    );

    const readInFlight = service.findCampaignsByIds(['c1']);
    await Promise.resolve();
    service.onCampaignCacheUpserted({ campaign: updated });
    finishLoading?.([stale]);

    const campaigns = await readInFlight;

    expect(campaigns[0].title).toBe('updated');
  });
});
